### ISSUE TITLE
포털 create account 후 verification email 없음.

### ISSUE THREAD

**Issue by SuyeongOh** [S-ResearchStack/web-portal#3]
안녕하세요. 
현직 앱 개발자이고, rPPG와 블록체인을 공부하고있는 오수영입니다.

s-healthstack에 대해 follow up을 하며, demo를 진행하고 있는 도중 web_portal관련 이슈 문의드립니다.
web_portal을 yarn dev명령어로 local network에서 열었는데, 동일 공유기 망 내에 타 PC에서 create account시 verification email전송이 되지않아 문의드립니다.

이부분이 이슈인지, 아니면 추가 작업진행 할것이 있는지 답변 부탁드립니다.

감사합니다.
오수영 드림.

**Comment by SuyeongOh** [comment]
또한 verification email이 전송되지 않았음에도 forget password 창에서 해당 email을 입력시 reset password link를 보냈다는 창으로 진행됩니다 하지만 메일은 마찬가지로 오지 않습니다.

**Comment by kiljong** [comment]
안녕하세요 답변이 늦었습니다.
이제 전체 코드가 완전히 변경되었으며 새로운 버전에서 해당 기능을 테스트 중입니다.
추후 백엔드와 웹포털쪽에서 해당 사항을 반영한 업데이트를 올릴 예정이니 그 때 확인해주시면 좋겠습니다.
감사합니다.
