### ISSUE TITLE
405 error output when registering for portal membership

### ISSUE THREAD

**Issue by yen1011** [S-ResearchStack/web-portal#4]
Hello,

After installing the Samsung backup system according to the instructions, the web portal was installed according to the instructions. IP Address: Port Number/Account/Write for normal access. However, if you normally enter your email, name, and password to create account to join the first account, the error "Failed to load resource: the server responded with a status of 405 (Not Allowed)" will occur.

I'll be waiting for the reply.

**Comment by kiljong** [comment]
Hello,
Sorry for late response.
Now, we have updated the project entirely.
Please check with the new one.
If you have a problem, please make an issue.
Thank you.
